### ISSUE TITLE
/makeserver doesn't do anything but make a copy of the version I am using

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/DevTools#10]
I dropped the src to devtools and all it did was make a copy of the version I am using

**Comment by dktapps** [comment]
[insert facepalm gif here]

**Comment by SOF3** [comment]
What else do you expect?

**Comment by HimbeersaftLP** [comment]
> [insert facepalm gif here]

Here we go: ![Facepalm gif](https://media0.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif)

**Comment by XDqrkneZ** [comment]
@SOF3 is that supposed to happen?

**Comment by XDqrkneZ** [comment]
@SOF3 that src is using the 1.1 protocol so why did it just make copy of the current version Imm using?

**Comment by XDqrkneZ** [comment]
:(
