### ISSUE TITLE
Problem when plugins fail strict type checks

### ISSUE THREAD

**Issue by Awzaw** [pmmp/DevTools#11]
DevTools disables itself if a plugin fails to load because of a type-declaration mismatch. Other plugins that loaded correctly before the broken plugin are sometimes disabled too, but with no discernible pattern. The console output for /plugins then shows DevTools and some other plugins as disabled, and no entry at all for the broken plugin.

**Comment by dktapps** [comment]
Wait... devtools loader _itself_ crashes if a plugin breaks???

**Comment by Awzaw** [comment]
If a plugin loaded from source fails to load because of a type-mismatch between function signature and the function call, yes.
