### ISSUE TITLE
Can't load DevTools

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/DevTools#15]
>Fatal error: Declaration of DevTools\DevTools::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar://H:/SorrowServer/plugins/DevTools_v1.12.1.phar/src/DevTools/DevTools.php on line 34

PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/cca9cf2c8683fe14c3698d8da52bfd45a2febb8d

**Comment by dktapps** [comment]
Congratulations for removing API checks without knowing what you're doing.

**Comment by Nerahikada** [comment]
I think you must provide latest DevTools.phar because we usually don't have means to make it.

**Comment by dktapps** [comment]
there's instructions how to build it in the README. Sad that nobody ever reads the README.
