### ISSUE TITLE
Feature Request: a way to temponary disable source plugin

### ISSUE THREAD

**Issue by tarik02** [pmmp/DevTools#17]
Sometimes i need to disable my plugin that open in my IDE, so i do not want to move plugin.
### Possibly solutions:
 - add field `disabled: true` to plugin.yml
 - add empty file `disabled` so plugin loader will ignore the plugin

**Comment by dktapps** [comment]
This doesn't make sense in such a specific context. Configuration to allow this has been discussed internally.
