### ISSUE TITLE
No files added ?

### ISSUE THREAD

**Issue by intagaming** [pmmp/DevTools#27]
From bash:

+ D:/Library/bin/php/php ./PocketMine-DevTools/src/DevTools/ConsoleScript.php --make ./repo/AlwaysSpawn_src --relative ./repo/AlwaysSpawn_src --out ./AlwaysSpawn.phar

Creating ./AlwaysSpawn.phar...
Adding files...
Added 0 files

Here's workspace:
https://drive.google.com/file/d/1f1UMkuGqP7S9fcBv67_zH_Z3WHFCWIFT/view?usp=sharing

Run at root folder.

**Comment by dktapps** [comment]
This issue tracker is not a support forum. Please use the [forums](https://forums.pmmp.io) for support.

**Comment by intagaming** [comment]
That's the latest commit, last commit working fine ? I mean 2d90902
