### ISSUE TITLE
How download .phar for api3?

### ISSUE THREAD

**Issue by Erkam246** [pmmp/DevTools#3]

**Comment by dktapps** [comment]
This is not a support forum any more than the Genisys one is. Do stop misusing issue trackers.

**Comment by Erkam246** [comment]
ok sry but idk how to get this i need it

**Comment by sylv256** [comment]
Omg idek how the heck u update the API. I know how to make it look like it in the code though.

**Comment by sylv256** [comment]
I'll try.

**Comment by sylv256** [comment]
Nvm
