### ISSUE TITLE
3.1.0?

### ISSUE THREAD

**Issue by Shelly7w7** [pmmp/DevTools#32]
Title says all

**Comment by NiclasOlofsson** [comment]
Pretty darn stupid

**Comment by Shelly7w7** [comment]
I think i closed it retard.

**Comment by buchwasa** [comment]
Everyone still saw the issue you opened and proceeded to close, retard.

**Comment by SOF3** [comment]
\*secretly changes the issue title to something else\*
\*everyone still sees the history\*

**Comment by Shelly7w7** [comment]
@SOF3 lol
