### ISSUE TITLE
Unable to extract/compile incompatible plugins since they aren't loaded

### ISSUE THREAD

**Issue by Ifera** [pmmp/DevTools#38]
### Description
DevTools will only extract plugins that are loaded on the server. It fails to extract and/or compile plugins that aren't loaded on the server. 

It is undesirable since many a times developers want to unphar old/broken plugins which wouldn't load due to incompatible api and thus will not be unphar-ed by DevTools since they aren't loaded on the server.

**Comment by SOF3** [comment]
If you want to decompile plugins that can't be loaded, simply use the command line interface. DevTools isn't really intended for this.

**Comment by dktapps** [comment]
and you wonder why people prefer pmt.mcpe.fun ?

**Comment by SOF3** [comment]
Let's make a plugin that adds a command `/phar` and pipes all the arguments to `phar.phar`. Happy?
I feel that we are going through a slippery slope there.

**Comment by dktapps** [comment]
That's a ridiculous argument. This issue is talking about extending the functionality, which is currently extremely limited, in a way which is perfectly reasonable given what devtools can already do.

**Comment by nathfreder** [comment]
Let's just kill DevTools and make a non-plugin tool.

**Comment by dktapps** [comment]
In retrospect, my argument in favour of implementing this feature essentially boiled down to "we already have one anti-feature, why not add another?". `/makeplugin` was already an anti-feature - having to start a server just to build a plugin never made any sense. No more so does it make sense to have to start a server to extract a plugin.
