### ISSUE TITLE
Command extractplugin does not work

### ISSUE THREAD

**Issue by Mgl642001** [pmmp/DevTools#5]
Hi,

I use the last version (1.11.2) and PocketMine 1.0.3 (API 3.0.0-ALPHA3), but when I do /extractplugin Name, nothing is shown, how to fix it ?

**Comment by dktapps** [comment]
Outdated version, get a phar from https://poggit.pmmp.io/ci/pmmp/PocketMine-DevTools/PocketMine-DevTools
