### ISSUE TITLE
Reload failed

### ISSUE THREAD

**Issue by zRains** [pmmp/DevTools#50]
I run the reload command after modifying the plugin's source code directly, but nothing changed in my server.

**Comment by john-bv** [comment]
Reload does not work as expected with pocketmine, reload simply disables and reenables plugins. Which is why reload on api 4.0.0 has been removed.

**Comment by zRains** [comment]
> Reload does not work as expected with pocketmine, reload simply disables and reenables plugins. Which is why reload on api 4.0.0 has been removed.

What is the way to quickly reload plug-ins without restarting the server? Thank you for your information
