### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by itsscristian** [pmmp/DevTools#58]
In the console I have a problem, an unrecoverable error has occurred and the server has crashed creating a dump. Upload the file (crash log file location) to the crash archive and post the link to the crash reporting page to provide as much information as you can. The crash dump has been automatically sent to the crash file. You can see it on (link failure page) or (id failure). Forcing the server to scream. I do not know what to do and if this problem is not solved, the console does not work.

**Comment by dktapps** [comment]
You know there's a reason it tells you to include the crash link, right?...

**Comment by itsscristian** [comment]
hey dktapps sorry your discord partner solved it for me thanks im silly

**Comment by itsscristian** [comment]
silly* 😅
