### ISSUE TITLE
Bug Command

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [pmmp/DevTools#63]
When using /checkperm a certain permission like pocketmine.command.say , the server will crash , I tested it at test.pmmp.io.

**Comment by dktapps** [comment]
This is not fixed yet

**Comment by skyss0fly** [comment]
Lol

**Comment by dktapps** [comment]
Fixed by https://github.com/pmmp/DevTools/commit/f9cda52d63e97b36bf0adc170eaba80977aee2c8
