### ISSUE TITLE
/makeplugin includes plugin-generated files too

### ISSUE THREAD

**Issue by SOF3** [pmmp/DevTools#8]
It's very reasonable that a folder plugin is named after the plugin name. Hence, the plugin will use its own folder as the data folder.

For example, some plugins run `$this->saveDefaultConfig()` when the plugin is enabled. The user runs /makeplugin, and the whole plugin folder, which is also used as the data folder, is included into the built phar.

It is suggested that only plugin.yml, resources/ and src/ be added into the phar when DevTools builds the plugin. Otherwise, it might accidentally include sensitive data (such as passphrases, including both those in the config file and saves files) into the phar.

**Comment by SOF3** [comment]
In the current DevTools workflow, it is impossible to avoid including the generated files unless you either rename the plugin folder or delete the generated files manually, where the latter might cause destructive damage to the server.

**Comment by robske110** [comment]
Because users might already be used to this behaviour it might be worth putting in a warning that tells the user if there are files in the Folder which will not be compiled or put in the phar, like “[NOTICE] There are other files in the FolderPlugin which will not be compiled/put into the phar!”

**Comment by jasonw4331** [comment]
What about adding licenses and README's? @SOF3

**Comment by dktapps** [comment]
A possible solution could be to use the plugin's .gitignore, although that would depend on the plugin being in a git repository.

**Comment by SOF3** [comment]
DevTools is actually inconvenient by nature. It seems to force the plugin workspace to be in the server's plugin directory.

**Comment by eternalharvest** [comment]
I always run this command to explicity specify the directory i want to include in my plugin.

```
php -dphar.readonly=0 DevTool.phar --relative myplugin --make myplugin/src,myplugin/resources,myplugin/vendor --out myplugin.phar
```

But this command do not include README.md or LICENSE files.
So, I use my own utility to add these files into myplugin.phar.

I suggest adding new 'make' directive in 'plugin.yml' file like below.

```yml
name: myplugin
version: 1.0.0-beta
api: [3.0.0-ALPHA11]
load: STARTUP
main: myplugin\main
make:
  - src
  - vendor
  - README.md
  - LICENSE
```
And I think It would be better if `--make` option of ConsoleScript.php accept files (not only include paths).
If make directive is not specified, whole plugin directory must be included for backward compatibility.
Of course `makeplugin` command also should use this directive to include directory / files.

**Comment by dktapps** [comment]
I'm thinking a better solution to this problem is to instead separate PocketMine-MP plugin data storage from plugin executables.

**Comment by dktapps** [comment]
PocketMine-MP 3.0.0 supports separated plugin data directories (although it's disabled by default for existing installations). I consider the original issue noted here therefore resolved.

However, there is a valid issue in that building a plugin still cannot be selective of the files it includes, only the directories.
