### ISSUE TITLE
Incompatible api version (3.0.0-ALPHA5)

### ISSUE THREAD

**Issue by ZGamerOficial** [pmmp/DevTools#9]
console cant load v 1.11.2 because is incompatible with api 3.0.0-alpha5

**Comment by corytortoise** [comment]
The master branch supports ALPHA5. You should make sure you are using the latest version.

**Comment by dktapps** [comment]
Compile it yourself or get a build from Poggit. Instructions for compiling are in the wiki.

**Comment by SOF3** [comment]
[The release on Poggit](https://poggit.pmmp.io/p/DevTools) has been released. Download the new release [here](https://poggit.pmmp.io/get/DevTools).
